### PR TITLE
Keep user data if needed

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/5624

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
See my comment here https://github.com/NethServer/dev/issues/5624#issuecomment-436905563

**Review by markVnl — COMMENTED** [review]
Hi,
I would like to discuss it a broader sense too;
Orphaning data by throwing away the key (username) and keeping the data seems a bad thing to do.

**Comment by gsanchietti** [comment]
I agree, this feature requires much more discussion before implementation.

**Comment by gsanchietti** [comment]
For now, all data should be kept in place.
Let's see if we can implement a specific task for data cleanup.

**Pull request closed without merging**
